load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//:markdownlint-cli2/package_json.bzl", markdownlint_cli2_bin = "bin")

package(default_visibility = ["//visibility:public"])

npm_link_all_packages(name = "node_modules")

markdownlint_cli2_bin.markdownlint_cli2_binary(
    name = "markdownlint-cli2",
)

bzl_library(
    name = "markdownlint_bzl",
    srcs = ["markdownlint.bzl"],
    deps = ["@bazel_utils_core//internal:workspace_tool"],
)

bzl_library(
    name = "markdown",
    srcs = ["markdown.bzl"],
    deps = [":markdownlint_bzl"],
)
