"""crate_universe hub for this plugin version."""

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
    name = "protoc_gen_protovalidate_buffa_v0_6_0",
    cargo_lockfile = "//plugins/protoc-gen-protovalidate-buffa/v0.6.0:Cargo.lock",
    generate_binaries = True,
    lockfile = "//plugins/protoc-gen-protovalidate-buffa/v0.6.0:cargo-bazel-lock.json",
    manifests = [
        "//plugins/protoc-gen-protovalidate-buffa/v0.6.0:Cargo.toml",
    ],
)

_PREFIX = "@bazel_utils_buf//plugins/protoc-gen-protovalidate-buffa/v0.6.0"

crate.annotation(
    build_script_data = ["{}:protoc_prefix".format(_PREFIX)],
    build_script_env = {
        "PROTOC": "$(execpath {}:protoc_prefix)/bin/protoc".format(_PREFIX),
    },
    crate = "protovalidate-buffa-protos",
    data_glob = ["proto/**"],
    label_injections = {"@bazel_utils_buf": "@bazel_utils_buf"},
    repositories = ["protoc_gen_protovalidate_buffa_v0_6_0"],
)
use_repo(crate, "protoc_gen_protovalidate_buffa_v0_6_0")
